### PR TITLE
Allow text-2.0

### PR DESCRIPTION
**Pull request by sjakobi**
https://hackage.haskell.org/package/text-2.0/changelog

### CODE REVIEW

**Comment by sjakobi** [comment]
@minad Could you publish this change as a Hackage revision or a new release?

**Comment by minad** [comment]
I am kind of busy right now with other things. Can you bump this as a trustee in the meantime? I will look again into this package in a while and create a proper release.

**Comment by sjakobi** [comment]
Alright, done: https://hackage.haskell.org/package/special-values-0.1.0.0/revisions/

**Comment by sjakobi** [comment]
Actually, I don't know whether a proper release is necessary at all. The revisions are sufficient for me.

**Pull request merged**
